version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_terroir
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: motdepasse
      MONGO_INITDB_DATABASE: terroir_local
    volumes:
      - mongo_terroir_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo_express_terroir
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: motdepasse
      ME_CONFIG_MONGODB_URL: mongodb://admin:motdepasse@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb

volumes:
  mongo_terroir_data:
